version: '3.8'

services:
  # Object Storage voor de scans
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

  # Database voor metadata en versioning
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Let op: zorg dat dit pad exact klopt met jouw systeem (output van 'pwd')
      - /home/student/ict_project/init:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

  # Database beheer interface
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

volumes:
  minio_data:
  postgres_data:
  pgadmin_data: