version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin_nick}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-VervangDitDoorEenVeiligWachtwoord123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - archief_net
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nick_archivaris}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-MijnGeheimeDatabaseWachtwoord456}
      POSTGRES_DB: ${POSTGRES_DB:-history_metadata_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - archief_net
    deploy:
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin_password_123}
    ports:
      - "8080:80"
    networks:
      - archief_net
    deploy:
      restart_policy:
        condition: on-failure

networks:
  archief_net:
    driver: overlay

volumes:
  minio_data:
  postgres_data: